services:
  nginx:
    build:
      context: ./docker/dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: ${APP_NAME}_nginx
    expose:
      - "80/tcp"
    ports:
      - "8080:80"
    volumes:
      - ./docker/configs/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/html:delegated
    depends_on:
      - php
      - mariadb
    networks:
      - maxmoll

  php:
    build:
      context: ./docker/dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: ${APP_NAME}_php
    expose:
      - "9000/tcp"
    volumes:
      - ./:/var/www/html:delegated
    networks:
      - maxmoll

  mariadb:
    image: mariadb:11.1.2
    container_name: ${APP_NAME}_mariadb
    restart: always
    expose:
      - "3306/tcp"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/database:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    depends_on:
      - phpmyadmin
    networks:
      - maxmoll

  phpmyadmin:
    image: phpmyadmin:5
    container_name: ${APP_NAME}_phpmyadmin
    restart: always
    expose:
      - "80/tcp"
    ports:
      - "8088:80"
    environment:
      - PMA_HOST=${DB_HOST}
    networks:
      - maxmoll

networks:
  maxmoll:
    name: maxmoll
    driver: bridge
